apiVersion: v1
kind: Service
metadata:
  name: mitrakv-headless
spec:
  clusterIP: None
  selector:
    app: mitrakv
  ports:
    - name: client
      port: 6379
    - name: raft
      port: 7379
    - name: metrics
      port: 9090c